<?php 

/**
 *  Provides a simple field for easily embedding images from IIIF Image Servers (currently supports Image API 2.0 only, with plans to support previous versions)
 *
 *  This module is not intended to replace media - it does not allow for any local storage of images, custom players or anything else
 *  It simply allows users to embed images from IIIF Image Servers - and provides a hook to allow other modules to provide more providers.
 *
 *  @author shaune
 */
/**
 *  Implementation of hook_menu
 *  create out admin page
 */
 function iiif_image_field_menu(){
   return array(
     'admin/config/media/iiif_image_field' => array(
       'title' => 'Configure IIIF Image Field',
       'description' => 'Configuration form for the IIIF Image Field, allows one to set viewer options.',
       'page callback' => 'drupal_get_form',
       'page arguments' => array('iiif_image_field_get_form'),
       'access arguments' => array('administer site configuration'),
     )
   );
 }

/**
 *  Implementation of hook_field_info
 *  Define the fields we're creating
 */
function iiif_image_field_field_info(){
  return array(
    'iiif_image_field' => array(
      'label' => 'IIIF Image Embed',
      'description' => 'Embed images from IIIF Image Server',
      'settings' => array(
        //no settings currently - not sure what we need
      ),
      'instance_settings' => array(
        'allowed_types' => array('libimages')
      ),
      'default_widget' => 'iiif_image_field_widget',
      'default_formatter' => 'iiif_image_field_formatter',
    )
  );
}

/**
 *  Implementation of hook_field_widget_info
 *  Define the widget for inputting 
 */
function iiif_image_field_field_widget_info(){
 return array(
   'iiif_image_field_widget' => array(
     'label' => 'IIIF Image Embed',
     'description' => 'Provides a IIIF Image embed field',
     'field types' => array('iiif_image_field'),
     'settings' => array(),
     'behaviors' => array(
       'multiple values' => FIELD_BEHAVIOR_DEFAULT,
       'default value' => FIELD_BEHAVIOR_DEFAULT
     )
   )
 );
}
/**
*  implementation of hook_field_widget_form
*/
function iiif_image_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element){
 //don't need to check the type right now because we're only defining one
 $element += array(
   // '#type' => 'iiif_image_field_widget'
    '#type' => $instance['widget']['type'],
    '#default_value' => isset($items[$delta]) ? $items[$delta] : '',
 );

 $element['iiif_image_id'] = array(
   '#type' => 'textfield',
   '#title' => 'Image ID',
   '#attached' => array(
     'css' => array(drupal_get_path('module', 'iiif_image_field') . '/iiif_image_field.form.css'),
     'js' => array(drupal_get_path('module', 'iiif_image_field') . '/iiif_image_field.form.js'),
    ),
    '#default_value' => isset($items[$delta]['iiif_image_id'])?$items[$delta]['iiif_image_id']:''
 );

 return $element;
}

function iiif_image_fields_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
 foreach ($items as $delta => $item) {
   //check that its a valid id     
 }
}

function iiif_image_field_field_is_empty($item, $field){
 return empty($item);
 if ($field['type'] == 'iiif_image_field') {

    if (empty($item['iiif_image_id']))
    {
      return TRUE;
    }
 }
    return FALSE;
}

//  IIIF Formatter Stuff

function iiif_image_field_field_formatter_info() {
 return array(
   'iiif_image_field_formatter' => array(
     'label' => t('IIIF Image Formatter'),
     'field types' => array('iiif_image_field'),
     'settings' => array(
          'zoom' => 0, 
          'rotation' => '0',
          'quality' => 'native',
          'format' => 'jpg'
        ),
     'multiple values' => FIELD_BEHAVIOR_DEFAULT,
   )
 );
}  


/**
*  Implements hook_field_formatter_settings_summary
*/

function iiif_image_field_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = '';
  if ($display['type'] == 'iiif_image_field_formatter') {
    if ($settings['zoom']) {
      $summary = t('Zoom: Yes');
    }
    else {
      $summary = t('Zoom: No');
    }

    $summary .= '<br />' . t('Rotation: @rotation', array('@rotation' => $settings['rotation']));
    $summary .= '<br />' . t('Quality: @quality', array('@quality' => $settings['quality']));
    $summary .= '<br />' . t('Format: @format', array('@format' => $settings['format']));
  }
  return $summary;
}


/**
 * Implements hook_field_formatter_settings_form
 */
function iiif_image_field_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element = array();

  if ($display['type'] == 'iiif_image_field_formatter') {
    $element['zoom'] = array(
      '#title' => t('Zoom'),
      '#type' => 'select',
      '#options' => array(
        0 => t('No'),
        1 => t('Yes')
      ),
      '#default_value' => $settings['zoom'],
      '#required' => TRUE,
    );
    $element['rotation'] = array(
      '#type' => 'textfield',
      '#size' => '5',
      '#title' => t('Rotation'),
      '#description' => t('The rotation of the image in degrees.  You may enter a number from 0 to 360.  A background will be visible behind images where degrees are not multiples of 90. '),
      '#default_value' => $settings['rotation'],
    );

    $element['quality'] = array(
      '#type'           => 'select',
      '#options'        => array(
          'native' => t('native'),
          'color' => t('color'),
          'grey' => t('grey'),
          'bitonal' => t('bitonal')
      ),
      '#title'          => t('Quality'),
      '#description'    => t('The quality parameter determines the mode of the image - color, greyscale, or black and white.'),
      '#default_value'  => $settings['quality'],
    );

    $element['format'] = array(
      '#type'           => 'select',
      '#options'        => array(
          'jpg' => t('jpg'),
          'png' => t('png'),
          'gif' => t('gif')
      ),
      '#title'          => t('Format'),
      '#description'    => t('The quality parameter determines the mode of the image - color, greyscale, or black and white.'),
      '#default_value'  => $settings['format'],
    );


  }

  return $element;

}



// Paint the field to the display

/**
*  Implements hook_field_formatter_view
*/


function iiif_image_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display){

  foreach ($items as $delta => $item) {

     $element[$delta] = 
      array(
        '#markup' => theme($display['type'], 
          array(
            'element' => $item, 
            'field' => $instance, 
            'settings' => $display['settings']
          )
        )
      );

  }

  return $element;

}

/**
 * Implements hook_theme().
 */

function iiif_image_field_theme() {
  return array(
    // The theme function that our formatter uses:
    'iiif_image_field_formatter' => array(
      // Don't forget that all Drupal 7 theme functions have only one argument,
      // so you declare what variables get passed within that argument instead.
      // See http://drupal.org/node/224333#theme_changes
      //'template' => 'iiif_image_field_formatter_iiif_image_field_formatter', 
      'variables' => array('element' => NULL, 'field' => NULL, 'settings' => NULL),
    ),
  );
}


/**
 * Theme function for 'iiif_image_field_formatter' link field formatter.
 */

function theme_iiif_image_field_formatter($variables) {
  dpm($variables);

  $zoom = "";
  if($variables['settings']['zoom']){
    $zoom = "zoom";
  }
  return "<img class='". $zoom . "' src='http://libimages.princeton.edu/loris/" . $variables['element']['iiif_image_id'] . "/full/200,/" . $variables['settings']['rotation'] . "/" . $variables['settings']['quality'] . "." . $variables['settings']['format'] . "'/>";
}


